--- #YAML:1.0
name: FDF-Simple
version: 0.01
author:
  - ~
abstract: ~
license: perl
requires:
  Class::MethodMaker: 0
  Parse::RecDescent: 1.94
  perl: 5.6.1
provides:
  FDF::Simple:
    file: lib/FDF/Simple.pm
    version: 0.01
generated_by: Module::Build version 0.23
